name: Build system

permissions:
  contents: write

on:
  push:
    branches:
      - main
    paths:
      - "version.txt"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set version from version.txt
        id: set_version
        run: |
          VERSION=$(cat version.txt)
          echo "Setting version to $VERSION"
          jq --arg ver "$VERSION" '.version = $ver' system.json > tmp.$$.json && mv tmp.$$.json system.json
          echo "tag=$VERSION" >> $GITHUB_OUTPUT
      - uses: actions/setup-node@v3
        with:
          node-version: "22"
      - run: npm install
      - run: npm run build
      - run: npm run packs:compile
      - run: zip -r foundry-fading-suns-4.zip dist
      - name: Create latest release
        id: create_latest_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: Latest
          draft: false
          prerelease: false
          artifacts: "./system.json,./foundry-fading-suns-4.zip"
          tag: latest
      - name: Create tag release
        id: create_tag_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: false
          name: ${{ steps.set_version.outputs.tag }}
          draft: false
          prerelease: false
          artifacts: "./system.json,./foundry-fading-suns-4.zip"
          tag: ${{ steps.set_version.outputs.tag }}
